Repository kure-kosen/cho_kure_web, pull requests merged in 2018-04, with the labels that each got.

#262 【2018/04/01】リリース
  .ruby-version
  app/views/layouts/admin.html.erb
  config/unicorn/production.rb
  config/unicorn/staging.rb
  frontend/src/components/personality-small.vue
  frontend/src/components/radio-preview.vue
  frontend/src/pages/personality.vue
  frontend/src/pages/radio.vue
  frontend/src/pages/top.vue
Labels: リリース

#248 ES6の記法を使えるようにした
  .babelrc
  frontend/src/packs/root.js
  package.json
  yarn.lock
Labels: wait for review

#263 【2018/04/03】リリース
  .babelrc
  frontend/src/app.vue
  frontend/src/packs/root.js
  package.json
  yarn.lock
Labels: リリース

#266 Attach preload='metadata' to audio tag
  app/views/admin/radios/show.html.erb
  frontend/src/components/radio-preview.vue
Labels: wait for review

#267 【2018/04/05】リリース
  .github/PULL_REQUEST_TEMPLATE.md
  app/views/admin/radios/show.html.erb
  frontend/src/components/radio-preview.vue
Labels: リリース

#268 Fix/fix onigiri channel
  config/deploy.rb
Labels: wait for review

#256 modelのテストを書く
  .rubocop.yml
  README.md
  app/models/personality.rb
  app/uploaders/community_logo_uploader.rb
  app/uploaders/personality_image_uploader.rb
  app/uploaders/radio_digest_mp3_uploader.rb
  app/uploaders/radio_image_uploader.rb
  app/uploaders/radio_mp3_uploader.rb
  spec/factories/audios/test.mp3
  spec/factories/personalities.rb
  spec/factories/radio_personalities.rb
  spec/factories/radios.rb
  spec/models/api/contact_form_item_spec.rb
  spec/models/personality_spec.rb
  spec/models/radio_spec.rb
  spec/rails_helper.rb
Labels: wait for review

#255 fix personality policy
  app/policies/admin/personality_policy.rb
Labels: wait for review

#273 Including nginx conf
  middleware/nginx/production.conf
  middleware/nginx/staging.conf
Labels: wait for review

#274 【2018/04/19】リリース
  .rubocop.yml
  README.md
  app/models/personality.rb
  app/policies/admin/personality_policy.rb
  app/uploaders/community_logo_uploader.rb
  app/uploaders/personality_image_uploader.rb
  app/uploaders/radio_digest_mp3_uploader.rb
  app/uploaders/radio_image_uploader.rb
  app/uploaders/radio_mp3_uploader.rb
  config/deploy.rb
  middleware/nginx/production.conf
  middleware/nginx/staging.conf
  spec/factories/audios/test.mp3
  spec/factories/personalities.rb
  spec/factories/radio_personalities.rb
  spec/factories/radios.rb
  spec/models/api/contact_form_item_spec.rb
  spec/models/personality_spec.rb
  spec/models/radio_spec.rb
  spec/rails_helper.rb
Labels: リリース

#278 Modify preload=metadata -> preload=none
  app/models/radio.rb
  app/serializers/radio_serializer.rb
  app/services/podcast/feed.rb
  frontend/src/components/radio-preview.vue
  frontend/src/pages/top.vue
  spec/models/radio_spec.rb
Labels: wait for review

#279 【2018/04/28】リリース
  app/controllers/admin/personalities_controller.rb
  app/controllers/api/v1/personalities_controller.rb
  app/enums/personality_roles.rb
  app/models/personality.rb
  app/models/radio.rb
  app/policies/admin/personality_policy.rb
  app/serializers/radio_serializer.rb
  app/services/podcast/feed.rb
  app/view_objects/admin/personality_view_object.rb
  app/views/admin/personalities/show.html.erb
  config/locales/enums/personality_roles.ja.yml
  config/routes.rb
  frontend/src/components/radio-preview.vue
  frontend/src/pages/top.vue
  spec/models/personality_spec.rb
  spec/models/radio_spec.rb
Labels: bug, リリース
