Repository kure-kosen/cho_kure_web, pull requests merged in 2018-03, with the labels that each got.

#232 ちょっくれとは」からpodcast登録方法へのリンク修正
  frontend/src/pages/about.vue
Labels: wait for review

#239 プライバシーポリシーページの改訂
  frontend/src/pages/policy.vue
Labels: review complete

#241 【2018/03/06】リリース
  frontend/src/pages/about.vue
  frontend/src/pages/policy.vue
Labels: リリース

#236 シェアボタンの位置の修正
  frontend/src/pages/radio.vue
Labels: wait for review

#238 adminのnavbarの修正
  app/views/layouts/admin.html.erb
Labels: WIP

#190 Feature/link as link
  .ruby-version
  frontend/src/components/personality-small.vue
  frontend/src/components/radio-preview.vue
  frontend/src/pages/personality.vue
  frontend/src/pages/radio.vue
  frontend/src/pages/top.vue
Labels: wait for review
