Repository kure-kosen/cho_kure_web, pull requests merged in 2019-06, with the labels that each got.

#352 Add sns id to personalities
  app/controllers/admin/personalities_controller.rb
  app/models/personality.rb
  app/serializers/personality_serializer.rb
  app/views/admin/personalities/_form.html.erb
  app/views/admin/personalities/show.html.erb
  config/locales/models/personality.ja.yml
  db/migrate/20190601164015_add_sns_to_personalities.rb
  db/schema.rb
Labels: Backend (Rails), design renewal

#348 dockerize of development
  .env.sample
  README.md
  config/database.yml
  docker-compose.yml
  docker/backend/Dockerfile.dev
  docker/mysql/Dockerfile.local
  docker/mysql/init.d/initialize.sql
  docker/mysql/log.cnf
  docker/mysql/my.cnf
Labels: Dockerize, review complete, 優先度高

#346 send-contactの修正
  frontend/package.json
  frontend/src/api/ContactApi.ts
  frontend/src/api/RestClient.ts
  frontend/src/commons/ChkButtonBase.tsx
  frontend/src/commons/color.ts
  frontend/src/components/ContactForm.tsx
  frontend/src/components/Forms/CheckBox.tsx
  frontend/src/components/Forms/Select.tsx
  frontend/src/components/Forms/TextInput.tsx
  frontend/src/components/Spinners/CircleSpinner.tsx
  frontend/src/entries/Contact.tsx
  frontend/src/models/ContactModel.ts
  frontend/src/stores/ContactStore.ts
  frontend/src/utils/validation.ts
  frontend/tsconfig.json
  frontend/tslint.json
  frontend/yarn.lock
Labels: design renewal, wait for review

#336 React/send contact
  app/controllers/api/v1/contacts_controller.rb
  app/models/contact.rb
  frontend/package.json
  frontend/src/api/ContactApi.ts
  frontend/src/api/RestClient.ts
  frontend/src/commons/ChkButtonBase.tsx
  frontend/src/commons/color.ts
  frontend/src/components/ContactForm.tsx
  frontend/src/components/Forms/CheckBox.tsx
  frontend/src/components/Forms/Select.tsx
  frontend/src/components/Forms/TextInput.tsx
  frontend/src/components/Spinners/CircleSpinner.tsx
  frontend/src/entries/Contact.tsx
  frontend/src/index.tsx
  frontend/src/layouts/Main.tsx
  frontend/src/models/ContactModel.ts
  frontend/src/stores/ContactStore.ts
  frontend/src/stores/RootStore.ts
  frontend/src/utils/validation.ts
  frontend/tsconfig.json
  frontend/tslint.json
  frontend/yarn.lock
Labels: Frontend (React), design renewal, wait for review

#353 Add personality new_face & regular
  app/controllers/api/v1/personalities_controller.rb
  app/models/personality.rb
  app/serializers/personality_serializer.rb
  config/routes.rb
Labels: Backend (Rails), design renewal

#361 Feature/duration seconds
  app/serializers/radio_serializer.rb
Labels: Backend (Rails), design renewal, wait for review

#369 【2019/06/25】リリース
  app/assets/stylesheets/admin/custom.css
  app/controllers/admin/base_controller.rb
  app/controllers/admin/radios_controller.rb
  app/controllers/api/v1/radios_controller.rb
  app/models/comic.rb
  app/models/radio.rb
  app/serializers/comic_serializer.rb
  app/serializers/radio_serializer.rb
  app/uploaders/comic_image_uploader.rb
  app/views/admin/radios/_form.html.erb
  app/views/admin/radios/show.html.erb
  db/fixtures/70_comic.rb
  db/fixtures/images/comic_01.jpg
  db/fixtures/images/comic_02.jpg
  db/fixtures/images/comic_03.jpg
  db/migrate/20180814052753_create_comics.rb
  db/schema.rb
  spec/factories/comics.rb
  spec/models/comic_spec.rb
Labels: リリース
