Repository kure-kosen/cho_kure_web, pull requests merged in 2019-05, with the labels that each got.

#335 popular radioの実装
  frontend/images/sidebar-radio-img.png
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/commons/ChkButtonBase.tsx
  frontend/src/commons/color.ts
  frontend/src/commons/font.ts
  frontend/src/commons/style.ts
  frontend/src/components/AboutBottom.tsx
  frontend/src/components/AboutSidebar.tsx
  frontend/src/components/ChkSlider.tsx
  frontend/src/components/FeaturedPersonalityButton.tsx
  frontend/src/components/FeaturedPersonalityListenToRadioButton.tsx
  frontend/src/components/HeroArea.tsx
  frontend/src/components/PopularRadioCard.tsx
  frontend/src/components/PopularRadioWrapper.tsx
  frontend/src/components/RadioHistoryContentWrapper.tsx
  frontend/src/components/RadioSearcher.tsx
  frontend/src/entries/Contact.tsx
  frontend/src/entries/Index.tsx
  frontend/src/index.tsx
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: design renewal, review complete

#316 FeaturedBlogWrapperの実装
  frontend/images/apple-2385198_1280-1.jpg
  frontend/src/commons/color.ts
  frontend/src/components/FeaturedBlog.tsx
  frontend/src/components/FeaturedBlogWrapper.tsx
  frontend/src/components/MoreButton.tsx
  frontend/src/components/PopularRadioWrapper.tsx
  frontend/src/components/RadioHistoryContentWrapper.tsx
Labels: WIP, design renewal

#340 feature/dockerizeの修正
  .env.sample
  README.md
  docker-compose.yml
  docker/backend/Dockerfile.dev
Labels: Dockerize, review complete
